# -*- coding: utf-8 -*-
"""completed in class activity 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrKBWYVN05vkdeFhXkLR4BePmDEm2Kw4

1) We have a triangle, and we want to calculate its area. First, assign the length of the
base of the triangle to the variable name base, and assign the height of the triangle to
the variable name height. Using the assigned values of base and height, calculate the
area of the triangle and display it on the screen. The triangle we want to calculate the
area for has a base length of 10 cm and a height of 4 cm.
"""

base = 10
height = 4
area = .5 *base * height
print(f"the area of the triangle with base{base}cm and hieght {height} c is: {area}cm^2")

"""2) Suppose you have a vegetable garden that is 50cm in length and 80cm in width. If you
want to enclose the entire garden with a fence, and each fence length is 15cm, how
many fences would you need to cover the whole garden?
"""

width = 80
length = 50
fenceLength = 15
perimeter = 2*(width + length)
FencesNeeded = perimeter / fenceLength
print(f"you will need {FencesNeeded} fences")

"""3) Write a Python script to calculate the number of quarters, dimes, and dollars required
to represent 835 cents.
Your task is to create a Python program that takes the total amount in cents (835 cents in this case) and converts it into the equivalent number of quarters, dimes, and dollars.
Utilize integer division (//) and the remainder operator (%) for this calculation.
For instance, when given 835 cents, the program should output something like:
Total Amount: 835 cents
Quarters: 1
Dimes: 1
Dollars: 8
You can just show number of cents after quarters, dimes and dollars, don’t need to do
nickels and pennies (you can if you want, it is the same logic)
"""

totalCents = 835
Dollars = totalCents // 100
remainingCents = totalCents % 100

Quarters= remainingCents // 25
remainingCents = remainingCents % 25

Dimes = remainingCents // 10
remainingCents = remainingCents % 10

print(f"total amount: {totalCents} cents")
print(f"Quarters: {Quarters}")
print(f"Dimes: {Dimes}")
print(f"Dollars: {dollars}")

"""4) Write a Python program that prints the following pattern using escape characters:

One

 Two

  Three
"""

print("One\n\tTwo\n\t\tThree")

"""5) Write a Python program that asks the user for their name and prints the following
message using escape characters:

"John" is a common name.
"""

name = input("please enter your name: ")
print(f'"{name}" is a common name.')

"""Write a Python program that defines a file path using escape characters and prints it:

C:\Users\Documents\MyFile.txt
"""

filepath = "C:\\Users\\Documents\\MyFile.txt"
print(filepath)