# -*- coding: utf-8 -*-
"""Copy of In_Class_Activity_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sz5VYx1d0MmhJ5dgqkKlKEiQvELlZvlK

##Instructions for In Class Activity 1

You must find all errors in your scripts. But because you are communicating with a machine, not a person, you have to be exact: the computer cannot understand you at all if there are errors, bugs, in your code. Or the computer may do exactly what you wrote, but not what you meant to do.

Add a comment to the file that describes what you did.

Change the file name to "your name In Class Activity 1" and hand in these corrected Python scripts!

Question 1
"""

x = 15
y = 5
z = 3
#y=0 made this a not since y is already established
k = x / y
print(k)

"""Question 2"""

x = 10
y = 20
z = 30
print(x, y, z) #fixed the indentation

"""Question 3"""

# This program converts miles to km

miles = 10
multiplier = 1.609344
km = miles * multiplier #multiplier was spelled wrong
print(km)

"""Question 4"""

x = 1
y = 10
z = 2
t = 15
print((x * t) / (y / z)) #was missing a ) to finish the equation
print('Done')

"""Question 5"""

fruit = "kiwi"
print(fruit, fruit, fruit) #fruit was spelled wrong 3 times